// Date: 5/1/2015 9:29:37
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package com.stijnhero.forgery.client.renderer;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWhetstoneBase extends ModelBase {
	// fields
	ModelRenderer LegBackRight;
	ModelRenderer LegBackLeft;
	ModelRenderer LegFrontRight;
	ModelRenderer LegFrontLeft;
	ModelRenderer BeamLeft;
	ModelRenderer BeamRight;
	ModelRenderer BeamBack;
	ModelRenderer BeamFront;

	public ModelWhetstoneBase() {
		textureWidth = 64;
		textureHeight = 32;

		LegBackRight = new ModelRenderer(this, 0, 0);
		LegBackRight.addBox(0F, 0F, 0F, 2, 8, 2);
		LegBackRight.setRotationPoint(4F, 16F, -5F);
		LegBackRight.setTextureSize(64, 32);
		LegBackRight.mirror = true;
		setRotation(LegBackRight, -0.1396263F, 0F, 0F);
		LegBackLeft = new ModelRenderer(this, 0, 0);
		LegBackLeft.addBox(0F, 0F, 0F, 2, 8, 2);
		LegBackLeft.setRotationPoint(-6F, 16F, -5F);
		LegBackLeft.setTextureSize(64, 32);
		LegBackLeft.mirror = true;
		setRotation(LegBackLeft, -0.1396263F, 0F, 0F);
		LegFrontRight = new ModelRenderer(this, 0, 0);
		LegFrontRight.addBox(0F, 0F, 0F, 2, 8, 2);
		LegFrontRight.setRotationPoint(4F, 17F, 13F);
		LegFrontRight.setTextureSize(64, 32);
		LegFrontRight.mirror = true;
		setRotation(LegFrontRight, 0.1396263F, 0F, 0F);
		LegFrontLeft = new ModelRenderer(this, 0, 0);
		LegFrontLeft.addBox(0F, 0F, 0F, 2, 8, 2);
		LegFrontLeft.setRotationPoint(-6F, 17F, 13F);
		LegFrontLeft.setTextureSize(64, 32);
		LegFrontLeft.mirror = true;
		setRotation(LegFrontLeft, 0.1396263F, 0F, 0F);
		BeamLeft = new ModelRenderer(this, 0, 0);
		BeamLeft.addBox(0F, 0F, 0F, 2, 2, 24);
		BeamLeft.setRotationPoint(4F, 16F, -7F);
		BeamLeft.setTextureSize(64, 32);
		BeamLeft.mirror = true;
		setRotation(BeamLeft, 0F, 0F, 0F);
		BeamRight = new ModelRenderer(this, 0, 0);
		BeamRight.addBox(0F, 0F, 0F, 2, 2, 24);
		BeamRight.setRotationPoint(-6F, 16F, -7F);
		BeamRight.setTextureSize(64, 32);
		BeamRight.mirror = true;
		setRotation(BeamRight, 0F, 0F, 0F);
		BeamBack = new ModelRenderer(this, 0, 0);
		BeamBack.addBox(0F, 0F, 0F, 8, 2, 2);
		BeamBack.setRotationPoint(-4F, 16F, -5F);
		BeamBack.setTextureSize(64, 32);
		BeamBack.mirror = true;
		setRotation(BeamBack, 0F, 0F, 0F);
		BeamFront = new ModelRenderer(this, 0, 0);
		BeamFront.addBox(0F, 0F, 0F, 8, 2, 2);
		BeamFront.setRotationPoint(-4F, 16F, 13F);
		BeamFront.setTextureSize(64, 32);
		BeamFront.mirror = true;
		setRotation(BeamFront, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		LegBackRight.render(f5);
		LegBackLeft.render(f5);
		LegFrontRight.render(f5);
		LegFrontLeft.render(f5);
		BeamLeft.render(f5);
		BeamRight.render(f5);
		BeamBack.render(f5);
		BeamFront.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
